from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from Test_Data import data
import pytest
import time

class Test_Prem:
    url = "https://opensource-demo.orangehrmlive.com"
    
    # Booting Method for running the Python Tests
    @pytest.fixture
    def booting_function(self):
        self.driver = webdriver.Chrome()
        yield
        self.driver.close()
    
    def test_get_title(self, booting_function):
        self.driver.get(self.url)
        assert self.driver.title == 'OrangeHRM'
        print("SUCCESS")
    
    def test_search(self, booting_function):
        self.driver.get(self.url)
        time.sleep(5)
        self.driver.find_element(by=By.NAME, value=data.Prem_Selectors.input_box_username).send_keys(data.Prem_Data.username)
        self.driver.find_element(by=By.NAME, value=data.Prem_Selectors.input_box_password).send_keys(data.Prem_Data.password)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.login_xpath).click()
        assert self.driver.title == 'OrangeHRM'
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('ADMIN')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('admin')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('PIM')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('pim')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('LEAVE')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('leave')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('TIME')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('time')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('RECRUIMENT')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('recruiment')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('MY INFO')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('my info')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('PERFORMANCE')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('performance')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('DASHBOARD')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('dashboard')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('DIRECTORY')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('directory')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('MAINTENANCE')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('maintenance')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('BUZZ')
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.CONTROL + "a")
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys(Keys.BACKSPACE)
        time.sleep(5)
        self.driver.find_element(by=By.XPATH, value=data.Prem_Selectors.searchbox_xpath).send_keys('buzz')
        time.sleep(5)
        print("SUCCESSFULLY SEARCH TEXT IN SEARCH BOX")


 
        

        
